env:
  node: true
  es6: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 2019
plugins:
  - only-warn
  # - jest
# overrides:
#   - files:
#       - '**/*.test.js'
#     env:
#       jest: true
rules:
  # tabs
  no-mixed-spaces-and-tabs:
    - warn
    - smart-tabs
  no-tabs: 0
  indent:
    - 1
    - tab
    - SwitchCase: 1
      VariableDeclarator: 1
  react/prop-types: 0
  # react/jsx-indent:
  #   - 1
  #   - tab
  # react/jsx-indent-props:
  #   - 1
  #   - tab

  # reject 'React' was used before define
  # no-use-before-define: off
  # '@typescript-eslint/no-use-before-define':
  #   - warn

  # jest
  # jest/no-disabled-tests: warn
  # jest/no-focused-tests: warn
  # jest/no-identical-title: warn
  # jest/prefer-to-have-length: warn
  # jest/valid-expect: warn

  # other
  brace-style:
  - error
  - stroustrup
  - allowSingleLine: true
  comma-dangle:
  - error
  - always-multiline
  comma-spacing: error
  comma-style: error
  curly:
  - error
  - multi-line
  - consistent
  dot-location:
  - error
  - property
  handle-callback-err: 'off'
  # indent:
  # - error
  # - tab
  max-nested-callbacks:
  - error
  - max: 4
  max-statements-per-line:
  - error
  - max: 2
  no-console: 'off'
  no-empty-function: error
  no-floating-decimal: error
  no-inline-comments: error
  no-lonely-if: error
  no-multi-spaces: error
  no-multiple-empty-lines:
  - error
  - max: 2
    maxEOF: 1
    maxBOF: 0
  no-shadow:
  - error
  - allow:
    - err
    - resolve
    - reject
  no-trailing-spaces:
  - error
  no-var: error
  object-curly-spacing:
  - error
  - always
  prefer-const: error
  quotes:
  - error
  - single
  semi:
  - error
  - always
  space-before-blocks: error
  space-before-function-paren:
  - error
  - anonymous: never
    named: never
    asyncArrow: always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  yoda: error
